package gui;

import client.*;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hussein
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form gui_login
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txt_friendname = new javax.swing.JTextField();
        btn_addFriend = new javax.swing.JButton();
        btn_removeFriend = new javax.swing.JButton();
        btn_removeFriend.setOpaque(true);
        jScrollPane2 = new javax.swing.JScrollPane();
        friends = new javax.swing.JTextArea();
        btn_viewFriends = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        btn_Login = new javax.swing.JButton();
        btn_Register = new javax.swing.JButton();
        text_Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass_Password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btn_Register1 = new javax.swing.JButton();
        panel_register = new javax.swing.JPanel();
        btn_actRegister = new javax.swing.JButton();
        pass_passwordregister = new javax.swing.JPasswordField();
        pass_passwordconfirmregistration = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        txt_registerlastname = new javax.swing.JTextField();
        txt_registerfirstname = new javax.swing.JTextField();
        txt_registeremail = new javax.swing.JTextField();
        combobox_gender = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        combobox_day = new javax.swing.JComboBox<>();
        combobox_month = new javax.swing.JComboBox<>();
        combobox_year = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txt_usernameregister = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        label_digit = new javax.swing.JLabel();
        label_symbol = new javax.swing.JLabel();
        label_lowercase = new javax.swing.JLabel();
        label_uppercase = new javax.swing.JLabel();
        label_8characters = new javax.swing.JLabel();
        label_passwordsmatch = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();

        jTabbedPane2.setBackground(new java.awt.Color(58, 58, 58));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel2.setBackground(new java.awt.Color(58, 58, 58));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(-5, -5, -5, -5));
        jPanel2.setAutoscrolls(true);

        btn_addFriend.setText("add friends");
        btn_addFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addFriendActionPerformed(evt);
            }
        });

        btn_removeFriend.setBackground(new java.awt.Color(0, 153, 51));
        btn_removeFriend.setForeground(new java.awt.Color(255, 51, 153));
        btn_removeFriend.setText("remove friend");
        btn_removeFriend.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_removeFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeFriendActionPerformed(evt);
            }
        });

        friends.setColumns(20);
        friends.setRows(5);
        jScrollPane2.setViewportView(friends);

        btn_viewFriends.setText("view friends");
        btn_viewFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewFriendsActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_viewFriends)
                .addGap(507, 507, 507))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_friendname, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_addFriend)
                                .addGap(31, 31, 31)
                                .addComponent(btn_removeFriend)))
                        .addGap(88, 88, 88))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btn_viewFriends)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txt_friendname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_addFriend)
                            .addComponent(btn_removeFriend))
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("  FRIENDS  ", jPanel2);

        jScrollPane1.setViewportView(jTabbedPane2);

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(1, 5, 21));
        setBounds(new java.awt.Rectangle(0, 0, 500, 560));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 557));
        setPreferredSize(new java.awt.Dimension(698, 629));
        setResizable(false);
        setSize(new java.awt.Dimension(595, 595));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        panel_login.setBackground(new java.awt.Color(33, 39, 53));
        panel_login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(148, 107, 166), 3, true));
        panel_login.setForeground(new java.awt.Color(204, 204, 204));
        panel_login.setMaximumSize(new java.awt.Dimension(492, 478));
        panel_login.setMinimumSize(new java.awt.Dimension(492, 478));
        panel_login.setPreferredSize(new java.awt.Dimension(698, 629));
        panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Login.setBackground(new java.awt.Color(204, 255, 153));
        btn_Login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(0, 102, 153));
        btn_Login.setText("Login");
        btn_Login.setToolTipText("");
        btn_Login.setActionCommand("btn_Login");
        btn_Login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        panel_login.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 260, 38));

        btn_Register.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Register.setForeground(new java.awt.Color(0, 102, 255));
        btn_Register.setText("Register");
        btn_Register.setActionCommand("btn_Register");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });
        panel_login.add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 260, 40));

        text_Username.setBackground(new java.awt.Color(33, 39, 53));
        text_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_Username.setForeground(new java.awt.Color(204, 204, 204));
        text_Username.setText("Username");
        text_Username.setBorder(null);
        text_Username.setCaretColor(new java.awt.Color(148, 107, 166));
        text_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_UsernameFocusLost(evt);
            }
        });
        text_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_UsernameActionPerformed(evt);
            }
        });
        panel_login.add(text_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 220, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Don't have an account?");
        panel_login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, 30));

        pass_Password.setBackground(new java.awt.Color(33, 39, 53));
        pass_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pass_Password.setForeground(new java.awt.Color(204, 204, 204));
        pass_Password.setText("Password");
        pass_Password.setToolTipText("");
        pass_Password.setBorder(null);
        pass_Password.setCaretColor(new java.awt.Color(148, 107, 166));
        pass_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pass_Password.setEchoChar((char)0);
        pass_Password.setName(""); // NOI18N
        pass_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_PasswordFocusLost(evt);
            }
        });
        pass_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_PasswordActionPerformed(evt);
            }
        });
        panel_login.add(pass_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 220, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/beetrootRes.png"))); // NOI18N
        panel_login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 150, 130));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        panel_login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 250, 10));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        panel_login.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 250, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Beetroot Login");
        panel_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(108, 67, 126));
        jLabel2.setText("BEETROOT");
        panel_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 210, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel_login.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        btn_Register1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Register1.setForeground(new java.awt.Color(0, 102, 255));
        btn_Register1.setText("Forgot Password?");
        btn_Register1.setActionCommand("btn_Register");
        btn_Register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Register1ActionPerformed(evt);
            }
        });
        panel_login.add(btn_Register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 260, 40));

        getContentPane().add(panel_login, "card2");

        panel_register.setBackground(new java.awt.Color(33, 39, 53));
        panel_register.setMinimumSize(new java.awt.Dimension(698, 628));
        panel_register.setPreferredSize(new java.awt.Dimension(698, 628));
        panel_register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_actRegister.setBackground(new java.awt.Color(204, 204, 204));
        btn_actRegister.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_actRegister.setForeground(new java.awt.Color(0, 102, 204));
        btn_actRegister.setText("Register");
        btn_actRegister.setBorder(null);
        btn_actRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actRegisterActionPerformed(evt);
            }
        });
        panel_register.add(btn_actRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 180, 40));

        pass_passwordregister.setBackground(new java.awt.Color(33, 39, 53));
        pass_passwordregister.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        pass_passwordregister.setForeground(new java.awt.Color(150, 150, 150));
        pass_passwordregister.setText("Password");
        pass_passwordregister.setBorder(null);
        pass_passwordregister.setCaretColor(new java.awt.Color(148, 107, 166));
        pass_passwordregister.setEchoChar((char)0);
        pass_passwordregister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_passwordregisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_passwordregisterFocusLost(evt);
            }
        });
        pass_passwordregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_passwordregisterActionPerformed(evt);
            }
        });
        panel_register.add(pass_passwordregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 220, 26));

        pass_passwordconfirmregistration.setBackground(new java.awt.Color(33, 39, 53));
        pass_passwordconfirmregistration.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        pass_passwordconfirmregistration.setForeground(new java.awt.Color(150, 150, 150));
        pass_passwordconfirmregistration.setText("Confirm Password");
        pass_passwordconfirmregistration.setBorder(null);
        pass_passwordconfirmregistration.setCaretColor(new java.awt.Color(148, 107, 166));
        pass_passwordconfirmregistration.setEchoChar((char)0);
        pass_passwordconfirmregistration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_passwordconfirmregistrationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_passwordconfirmregistrationFocusLost(evt);
            }
        });
        pass_passwordconfirmregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_passwordconfirmregistrationActionPerformed(evt);
            }
        });
        panel_register.add(pass_passwordconfirmregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 210, 26));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Go Login");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_register.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 140, 40));

        jCheckBox1.setBackground(new java.awt.Color(33, 39, 53));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setText("I Agree to the fake terms and conditions");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        panel_register.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        txt_registerlastname.setBackground(new java.awt.Color(33, 39, 53));
        txt_registerlastname.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txt_registerlastname.setForeground(new java.awt.Color(150, 150, 150));
        txt_registerlastname.setText("Last Name");
        txt_registerlastname.setBorder(null);
        txt_registerlastname.setCaretColor(new java.awt.Color(148, 107, 166));
        txt_registerlastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_registerlastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_registerlastnameFocusLost(evt);
            }
        });
        txt_registerlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registerlastnameActionPerformed(evt);
            }
        });
        panel_register.add(txt_registerlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 230, 26));

        txt_registerfirstname.setBackground(new java.awt.Color(33, 39, 53));
        txt_registerfirstname.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txt_registerfirstname.setForeground(new java.awt.Color(150, 150, 150));
        txt_registerfirstname.setText("First Name");
        txt_registerfirstname.setBorder(null);
        txt_registerfirstname.setCaretColor(new java.awt.Color(148, 107, 166));
        txt_registerfirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_registerfirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_registerfirstnameFocusLost(evt);
            }
        });
        panel_register.add(txt_registerfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 220, 26));

        txt_registeremail.setBackground(new java.awt.Color(33, 39, 53));
        txt_registeremail.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txt_registeremail.setForeground(new java.awt.Color(150, 150, 150));
        txt_registeremail.setText("Email");
        txt_registeremail.setBorder(null);
        txt_registeremail.setCaretColor(new java.awt.Color(148, 107, 166));
        txt_registeremail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_registeremailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_registeremailFocusLost(evt);
            }
        });
        txt_registeremail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registeremailActionPerformed(evt);
            }
        });
        panel_register.add(txt_registeremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 250, 26));

        combobox_gender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combobox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unspecified", "Female", "Male" }));
        panel_register.add(combobox_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Gender:");
        panel_register.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Date of Birth:");
        panel_register.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        combobox_day.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combobox_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        panel_register.add(combobox_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        combobox_month.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combobox_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        combobox_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_monthActionPerformed(evt);
            }
        });
        panel_register.add(combobox_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        combobox_year.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combobox_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905" }));
        panel_register.add(combobox_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beetroot-02-02.png"))); // NOI18N
        jLabel15.setText("Beetroot Register");
        panel_register.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        txt_usernameregister.setBackground(new java.awt.Color(33, 39, 53));
        txt_usernameregister.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txt_usernameregister.setForeground(new java.awt.Color(150, 150, 150));
        txt_usernameregister.setText("Username");
        txt_usernameregister.setToolTipText("");
        txt_usernameregister.setBorder(null);
        txt_usernameregister.setCaretColor(new java.awt.Color(148, 107, 166));
        txt_usernameregister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameregisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameregisterFocusLost(evt);
            }
        });
        txt_usernameregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameregisterActionPerformed(evt);
            }
        });
        panel_register.add(txt_usernameregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(33, 39, 53));
        jTextField2.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Start your journey with a Beetroot Account");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panel_register.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 310, -1));

        jTextField3.setBackground(new java.awt.Color(33, 39, 53));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 0, 0));
        jTextField3.setBorder(null);
        jTextField3.setFocusable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        panel_register.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 210, 30));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        panel_register.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, -1));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        panel_register.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 250, 10));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        panel_register.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 220, 10));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));
        panel_register.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 210, -1));

        jSeparator7.setBackground(new java.awt.Color(204, 204, 204));
        panel_register.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 220, 10));

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));
        panel_register.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 230, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Password must contain at least:");
        panel_register.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        label_digit.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        label_digit.setForeground(new java.awt.Color(204, 204, 204));
        label_digit.setText("One digit");
        panel_register.add(label_digit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        label_symbol.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        label_symbol.setForeground(new java.awt.Color(204, 204, 204));
        label_symbol.setText("One symbol");
        panel_register.add(label_symbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        label_lowercase.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        label_lowercase.setForeground(new java.awt.Color(204, 204, 204));
        label_lowercase.setText("One lowercase letter");
        panel_register.add(label_lowercase, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        label_uppercase.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        label_uppercase.setForeground(new java.awt.Color(204, 204, 204));
        label_uppercase.setText("One uppercase letter");
        panel_register.add(label_uppercase, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        label_8characters.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        label_8characters.setForeground(new java.awt.Color(204, 204, 204));
        label_8characters.setText("8 characters");
        panel_register.add(label_8characters, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 100, -1));

        label_passwordsmatch.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        label_passwordsmatch.setForeground(new java.awt.Color(204, 204, 204));
        label_passwordsmatch.setText("Passwords must match");
        panel_register.add(label_passwordsmatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        label_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_email.setForeground(new java.awt.Color(255, 0, 0));
        panel_register.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 210, 30));

        getContentPane().add(panel_register, "card3");

        setBounds(0, 0, 714, 672);
    }// </editor-fold>//GEN-END:initComponents

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
       

    }

    private void btn_addFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addFriendActionPerformed
        // TODO add your handling code here:
//        String friend =txt_friendname.getText();
//        t.request("addFriend "+user+" "+friend);

    }//GEN-LAST:event_btn_addFriendActionPerformed

    private void btn_removeFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeFriendActionPerformed
        // TODO add your handling code here:
//        String friend =txt_friendname.getText();
//        t.request("removeFriend "+user+" "+friend);
    }//GEN-LAST:event_btn_removeFriendActionPerformed

    private void btn_viewFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewFriendsActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_viewFriendsActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        JFrame frame = (JFrame) evt.getSource();
        int result = JOptionPane.showConfirmDialog(
                frame,
                "Are you sure you want to exit the application?",
                "Exit Application",
                JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            if (t.isConnected == true) {
                t.terminate();
                chatclient cc = null;
                for (int i = 0; i < ct.size(); i++) {
                    cc = ct.get(i);
                    cc.terminate();
                    //useless here
                }
            }
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        }
    }//GEN-LAST:event_formWindowClosing

    private void combobox_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_monthActionPerformed

    private void txt_registeremailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registeremailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registeremailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panel_register.setVisible(false);
        panel_login.setVisible(true); // simple button to switch to login screen
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pass_passwordregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_passwordregisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_passwordregisterActionPerformed

    private void btn_actRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actRegisterActionPerformed
        // TODO add your handling code here:
        //username/pass/first/last/dof/gender/number/email dof: MM/DD/YYYY

        String username = txt_usernameregister.getText();
        String password = String.valueOf(pass_passwordregister.getPassword());
        String password_confirm = String.valueOf(pass_passwordregister.getPassword());
        String email = txt_registeremail.getText();
        String firstname = txt_registerfirstname.getText();
        String lastname = txt_registerlastname.getText();
        String gender = combobox_gender.getSelectedItem().toString();
        String day = combobox_day.getSelectedItem().toString();
        String month = combobox_month.getSelectedItem().toString();
        String year = combobox_year.getSelectedItem().toString();
        String dof = month + "/" + day + "/" + year;

        // now we start checking if given info is valid before we send request to the server
        if (t.start()) {

            if (username.equals("") || password.equals("") || password_confirm.equals("") || email.equals("") || firstname.equals("") || lastname.equals("") || year.equals("1800")) //required fields
            {
                JOptionPane.showMessageDialog(null, "One or more fields are missing", "Unsuccesful registration", JOptionPane.PLAIN_MESSAGE);
                
            } 
            else if (username.contains(" ") || password.contains(" ") || password_confirm.contains(" ")) // fix for required fields
            {
                JOptionPane.showMessageDialog(null, "One or more fields contain whitespaces", "Unsuccesful registration", JOptionPane.PLAIN_MESSAGE);
            }
            
            
            else if (!check_pass(password)) {
            
            
            }
            
            
            else if (password.equals(password_confirm) != true) {
                JOptionPane.showMessageDialog(null, "Passwords don't match", "Unsuccesful registration", JOptionPane.PLAIN_MESSAGE);
            } 
           
             else if (jCheckBox1.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Please agree to the terms", "Unsuccesful registration", JOptionPane.PLAIN_MESSAGE);
            }
             
             else { //ready to register
                request response = t.sendRequest(new request("register", username, password, firstname, lastname, dof, gender, "", email));
                if (response.response.equals("true")) {

                    JOptionPane.showMessageDialog(null, "Registration Successful", "A Gamer is born", JOptionPane.PLAIN_MESSAGE);
                } 
                else {
                    JOptionPane.showMessageDialog(null, "Could not complete registration, please check all fields again, perhaps an already used username", "Unsuccesful registration", JOptionPane.WARNING_MESSAGE);

                    t.terminate(); //no need to keep connection 
                }
            }
        } 
      
        else {
            JOptionPane.showMessageDialog(null, "Can't connect to server", "NO CONNECTION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_actRegisterActionPerformed
    private boolean check_pass(String pass) {
        if (pass.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password is less than 8 characters", "Unsuccesful registration", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        boolean upper = false;
        boolean lower = false;
        boolean symbol = false;
        boolean number = false;
        char c;
        for (int i = 0; i < pass.length(); i++) {
            c = pass.charAt(i);
            if (Character.isDigit(c)) {
                number = true;
            } else {
                if (Character.isUpperCase(c)) {
                    upper = true;
                } else {
                    if (Character.isLowerCase(c)) {
                        lower = true;
                    } else {
                        symbol = true;
                    }
                }
            }
        }
        if (upper == false) {
            JOptionPane.showMessageDialog(null, "Password must contain at least one Uppercase letter", "Unsuccesful registration", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        if (lower == false) {
            JOptionPane.showMessageDialog(null, "Password must contain at least one Lowercase letter", "Unsuccesful registration", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        if (number == false) {
            JOptionPane.showMessageDialog(null, "Password must contain at least one Number", "Unsuccesful registration", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        if (symbol == false) {
            JOptionPane.showMessageDialog(null, "Password must contain at least one Symbol", "Unsuccesful registration", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        return true;

    }
    private void pass_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_PasswordActionPerformed

    private void text_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_UsernameActionPerformed

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        text_Username.setText("Username");
        lel = 0;
        pass_Password.setText("Password");
        pass_Password.setEchoChar((char) 0);
        panel_register.setVisible(true);
        panel_login.setVisible(false); // hide this pannel (login) and go to the register page
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        String username = text_Username.getText();
        String password =String.valueOf(pass_Password.getPassword());
        if (t.start()) {
            if (username==null || password==null)
            {
                
                JOptionPane.showMessageDialog(null, "Wrong Username/Password combination.", "Unsuccesful login", JOptionPane.WARNING_MESSAGE);
            }
            
            
            else if(password.equals("") || username.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Wrong Username/Password combination.", "Unsuccesful login", JOptionPane.WARNING_MESSAGE);
            }
            
            else if (password.contains(" ") || username.contains(" ")) //check first if user enters more than word in user/pass fields : protect against injections later on
            {
                JOptionPane.showMessageDialog(null, "Wrong Username/Password combination.", "Unsuccesful login", JOptionPane.WARNING_MESSAGE);
            }
            
            else {
                request response = t.sendRequest(new request("login", username, password)); //send request to client for login

                if (response.response.equals("true")) {
                    //JOptionPane.showMessageDialog(null,"","LOGIN SUCCESFUL",JOptionPane.WARNING_MESSAGE);
                    user = username;
                    //JOptionPane.showMessageDialog(null, "Login Successful", "Welcome", JOptionPane.PLAIN_MESSAGE);
                    this.dispose(); //change pages
                    mainpage eng = new mainpage();
                    eng.setVisible(true);
                    //panel_login.setVisible(false);
                    // panel_mainPage.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Username/Password combination.", "Unsuccesful login", JOptionPane.WARNING_MESSAGE);
                    t.terminate();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Can't connect to server", "NO CONNECTION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void pass_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_PasswordFocusGained
        // TODO add your handling code here:
        pass_Password.setForeground(new Color(148, 107, 166));
        jSeparator1.setBackground(new Color(148, 107, 166));
        if (!pass_Password.echoCharIsSet()) {
            pass_Password.setText("");
            pass_Password.setEchoChar('•');
        }
    }//GEN-LAST:event_pass_PasswordFocusGained

    private void pass_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_PasswordFocusLost
        // TODO add your handling code here:
        pass_Password.setForeground(new Color(204, 204, 204));
        jSeparator1.setBackground(new Color(204, 204, 204));
        if (pass_Password.getText().isEmpty()) {
            pass_Password.setText("Password");
            pass_Password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_pass_PasswordFocusLost
    int lel = 0;
    private void text_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_UsernameFocusGained
        // TODO add your handling code here:
        if (lel == 0) {
            text_Username.setText("");

        }
        jSeparator2.setBackground(new Color(148, 107, 166));
        text_Username.setForeground(new Color(148, 107, 166));
    }//GEN-LAST:event_text_UsernameFocusGained

    private void text_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_UsernameFocusLost
        // TODO add your handling code here:
        text_Username.setForeground(new Color(204, 204, 204));
        jSeparator2.setBackground(new Color(204, 204, 204));
        if (text_Username.getText().equals("")) {
            text_Username.setText("Username");
            lel = 0;
        } else {
            lel = 1;
        }
    }//GEN-LAST:event_text_UsernameFocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void pass_passwordconfirmregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_passwordconfirmregistrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_passwordconfirmregistrationActionPerformed

    private void txt_registerlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registerlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registerlastnameActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    int lol = 0;
    private void txt_usernameregisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameregisterFocusGained
        // TODO add your handling code here:
        jSeparator3.setBackground(new Color(148, 107, 166));
        if (lol == 0) {
            txt_usernameregister.setText("");
            txt_usernameregister.setFont(new Font("Tahoma", Font.PLAIN, 18));
            lol = 1;
        }
        txt_usernameregister.setForeground(new Color(148, 107, 166));

    }//GEN-LAST:event_txt_usernameregisterFocusGained

    private void txt_usernameregisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameregisterFocusLost
        // TODO add your handling code here:
        txt_usernameregister.setForeground(new Color(204, 204, 204));
        if (txt_usernameregister.getText().equals("")) {
            txt_usernameregister.setFont(new Font("Tahoma", Font.ITALIC, 18));
            txt_usernameregister.setText("Username");
            txt_usernameregister.setForeground(new Color(150, 150, 150));
            lol = 0;
            jSeparator3.setBackground(new Color(204, 204, 204));
            jTextField3.setText("");
        }
        else{
            if (txt_usernameregister.getText().contains(" ")) {
                jTextField3.setText("Please remove whitespaces");
                jSeparator3.setBackground(Color.red);
               // jTextField3.setBackground(new Color(54, 14, 16));
            } else {
                if (txt_usernameregister.getText().length() > 18) {
                    jTextField3.setText("Username too long");
                    jSeparator3.setBackground(Color.red);
                //  jTextField3.setBackground(new Color(54, 14, 16));
                } else {
                    jTextField3.setText("");
                    jSeparator3.setBackground(Color.green);
                //    jTextField3.setBackground(new Color(33, 39, 53));
                }
            }
        }

    }//GEN-LAST:event_txt_usernameregisterFocusLost
    int eemail = 0;
    private void txt_registeremailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_registeremailFocusGained
        // TODO add your handling code here:
        jSeparator4.setBackground(new Color(148, 107, 166));
        txt_registeremail.setForeground(new Color(148, 107, 166));
        if (eemail == 0) {
            txt_registeremail.setText("");
            txt_registeremail.setFont(new Font("Tahoma", Font.PLAIN, 18));
        }
    }//GEN-LAST:event_txt_registeremailFocusGained
    private boolean emailCheck(String get)
    {
        int count=0;
        char a='@';
        int atpos = 0, dotpos = 0, flag = 0;
        for(int i = 0; i < get.length(); i++) {
            if(get.charAt(i) == a) {
                count++;
                atpos = i;
                if(count >= 2) {
                    flag = 1;
                    break;
                }
            }
           if (get.charAt(i) == '.') {
               dotpos = i;
            }
        }  
        if (atpos < 1 || dotpos < atpos + 2 || dotpos + 2 >= get.length() || flag == 1) {
         //   message = "Not a valid e-mail address";
         return false;
        } 
        else {
            return true;
  //          message = "valid email-id";
        }
//        return message;
    }
    private void txt_registeremailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_registeremailFocusLost
        // TODO add your handling code here:
        txt_registeremail.setForeground(new Color(204, 204, 204));
        if (txt_registeremail.getText().equals("")) {
            txt_registeremail.setFont(new Font("Tahoma", Font.ITALIC, 18));
            txt_registeremail.setText("Email");
            txt_registeremail.setForeground(new Color(150, 150, 150));
            eemail = 0;
            jSeparator4.setBackground(new Color(204, 204, 204));
            label_email.setText("");
        } else {
            eemail = 1;
            if(!emailCheck(txt_registeremail.getText()))
            {
                label_email.setText("Invalid email");
                jSeparator4.setBackground(Color.red);
            }
            else
            {
                label_email.setText("");
                jSeparator4.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_txt_registeremailFocusLost

    private void pass_passwordregisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_passwordregisterFocusGained
        // TODO add your handling code here:
        jSeparator5.setBackground(new Color(148, 107, 166));
        pass_passwordregister.setForeground(new Color(148, 107, 166));
        pass_passwordregister.setFont(new Font("Tahoma", Font.PLAIN, 18));
        if (!pass_passwordregister.echoCharIsSet()) {
            pass_passwordregister.setText("");
            pass_passwordregister.setEchoChar('•');
        }
    }//GEN-LAST:event_pass_passwordregisterFocusGained

    private void pass_passwordregisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_passwordregisterFocusLost
        // TODO add your handling code here:
        jSeparator5.setBackground(new Color(204, 204, 204));
        pass_passwordregister.setForeground(new Color(204, 204, 204));
        if (pass_passwordregister.getText().isEmpty()) {
            pass_passwordregister.setText("Password");
            pass_passwordregister.setEchoChar((char) 0);
            pass_passwordregister.setForeground(new Color(150, 150, 150));
            pass_passwordregister.setFont(new Font("Tahoma", Font.ITALIC, 18));
            label_8characters.setForeground(new Color(204,204,204));
            label_uppercase.setForeground(new Color(204,204,204));
            label_symbol.setForeground(new Color(204,204,204));
            label_lowercase.setForeground(new Color(204,204,204));
            label_digit.setForeground(new Color(204,204,204));
        }
        else{
        ////for password checking:
        String mzannar = String.valueOf(pass_passwordregister.getPassword());
        //String mzannar= pass_passwordregister.getText();
        passRegisterCheck(mzannar);
        }
    }//GEN-LAST:event_pass_passwordregisterFocusLost
    private void passRegisterCheck(String a) {
        jSeparator5.setBackground(Color.green);
        if (a.length() < 8) {
            label_8characters.setForeground(Color.RED);
            jSeparator5.setBackground(Color.red);
        } else {
            label_8characters.setForeground(Color.GREEN);
        }

        boolean uppercase = false;
        boolean lowercase = false;
        boolean symboll = false;
        boolean numberr = false;
        char cc;
        for (int i = 0; i < a.length(); i++) {
            cc = a.charAt(i);
            if (Character.isDigit(cc)) {
                numberr = true;
            } else if (Character.isUpperCase(cc)) {
                uppercase = true;
            } else if (Character.isLowerCase(cc)) {
                lowercase = true;
            } else {
                symboll = true;
            }

        }
    
        if(uppercase==false)
        {
            label_uppercase.setForeground(Color.red);
            jSeparator5.setBackground(Color.red);
        }
        else
            label_uppercase.setForeground(Color.green);
        if(lowercase==false)
        {
             label_lowercase.setForeground(Color.red);
            jSeparator5.setBackground(Color.red);
        }
        else
            label_lowercase.setForeground(Color.green);
        if(numberr==false)
        {
         label_digit.setForeground(Color.red);
        jSeparator5.setBackground(Color.red);
        }
        else
            label_digit.setForeground(Color.green);
        if(symboll==false)
        {
            label_symbol.setForeground(Color.RED);
            jSeparator5.setBackground(Color.red);
        }
        else
            label_symbol.setForeground(Color.green);
    
    }
    private void pass_passwordconfirmregistrationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_passwordconfirmregistrationFocusGained
        // TODO add your handling code here:
        jSeparator6.setBackground(new Color(148,107,166));
        pass_passwordconfirmregistration.setForeground(new Color(148, 107, 166));
        pass_passwordconfirmregistration.setFont(new Font("Tahoma",Font.PLAIN,18));
        if(!pass_passwordconfirmregistration.echoCharIsSet())
        {
            pass_passwordconfirmregistration.setText("");
            pass_passwordconfirmregistration.setEchoChar('•');
        }
        
    }//GEN-LAST:event_pass_passwordconfirmregistrationFocusGained

    private void pass_passwordconfirmregistrationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_passwordconfirmregistrationFocusLost
        // TODO add your handling code here:
        pass_passwordconfirmregistration.setForeground(new Color(204, 204, 204));
        if(pass_passwordconfirmregistration.getText().isEmpty())
        {
            jSeparator6.setBackground(new Color(204,204,204));
            pass_passwordconfirmregistration.setText("Confirm Password");
            pass_passwordconfirmregistration.setEchoChar((char)0);
            pass_passwordconfirmregistration.setForeground(new Color(150,150,150));
            pass_passwordconfirmregistration.setFont(new Font("Tahoma",Font.ITALIC,18));
             label_passwordsmatch.setForeground(new Color(204,204,204));
        }
        else{
            if(String.valueOf(pass_passwordconfirmregistration.getPassword()).equals(String.valueOf(pass_passwordregister.getPassword()))){
                label_passwordsmatch.setForeground(Color.green);
                jSeparator6.setBackground(Color.green);
            }
            else
            {
                label_passwordsmatch.setForeground(Color.red);
                jSeparator6.setBackground(Color.RED);
            }
        }
    }//GEN-LAST:event_pass_passwordconfirmregistrationFocusLost
    int fistnem=0;
    private void txt_registerfirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_registerfirstnameFocusGained
        // TODO add your handling code here:
        jSeparator7.setBackground(new Color(148,107,166));
        txt_registerfirstname.setForeground(new Color(148,107,166));
        if(fistnem==0)
        {
            txt_registerfirstname.setText("");
            txt_registerfirstname.setFont(new Font("Tahoma",Font.PLAIN,18));
        }
    }//GEN-LAST:event_txt_registerfirstnameFocusGained

    private void txt_registerfirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_registerfirstnameFocusLost
        // TODO add your handling code here:
        jSeparator7.setBackground(new Color(204,204,204));
        txt_registerfirstname.setForeground(new Color(204,204,204));
        if(txt_registerfirstname.getText().isEmpty())
        {
            txt_registerfirstname.setFont(new Font("Tahoma",Font.ITALIC,18));
            txt_registerfirstname.setText("First Name");
            txt_registerfirstname.setForeground(new Color(150,150,150));
            fistnem=0;
            jSeparator7.setBackground(new Color(204,204,204));
        }
        else
        {
            fistnem=1;
            if(txt_registerfirstname.getText().contains(" "))
            {
                jSeparator7.setBackground(Color.red);
            }
            else
                jSeparator7.setBackground(Color.green);
        }
    }//GEN-LAST:event_txt_registerfirstnameFocusLost
    int lisztnem=0;
    private void txt_registerlastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_registerlastnameFocusGained
        // TODO add your handling code here:
        jSeparator8.setBackground(new Color(148,107,166));
        txt_registerlastname.setForeground(new Color(148,107,166));
        if(lisztnem==0)
        {
            txt_registerlastname.setText("");
            txt_registerlastname.setFont(new Font("Tahoma",Font.PLAIN,18));
        }
    }//GEN-LAST:event_txt_registerlastnameFocusGained

    private void txt_registerlastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_registerlastnameFocusLost
        // TODO add your handling code here:
        
        txt_registerlastname.setForeground(new Color(204,204,204));
        if(txt_registerlastname.getText().isEmpty())
        {
            txt_registerlastname.setFont(new Font("Tahoma",Font.ITALIC,18));
            txt_registerlastname.setText("Last Name");
            txt_registerlastname.setForeground(new Color(150,150,150));
            lisztnem=0;
            jSeparator8.setBackground(new Color(204,204,204));
        }
        else
        {
            lisztnem=1;
            if(txt_registerlastname.getText().contains(" "))
                jSeparator8.setBackground(Color.red);
            else
                jSeparator8.setBackground(Color.green);
        }
    }//GEN-LAST:event_txt_registerlastnameFocusLost

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void txt_usernameregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameregisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameregisterActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_Register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Register1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Register1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private ArrayList<chatclient> ct=new ArrayList<chatclient>();
    public static String user="";
    public static client t = new client("127.0.0.1", 1555); //immediate connection when entering
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new GUI().setVisible(true);
                
                //client t = new client("localhost", 1555); //immediate connection when entering
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_Register;
    private javax.swing.JButton btn_Register1;
    private javax.swing.JButton btn_actRegister;
    private javax.swing.JButton btn_addFriend;
    private javax.swing.JButton btn_removeFriend;
    private javax.swing.JButton btn_viewFriends;
    private javax.swing.JComboBox<String> combobox_day;
    private javax.swing.JComboBox<String> combobox_gender;
    private javax.swing.JComboBox<String> combobox_month;
    private javax.swing.JComboBox<String> combobox_year;
    private javax.swing.JTextArea friends;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel label_8characters;
    private javax.swing.JLabel label_digit;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_lowercase;
    private javax.swing.JLabel label_passwordsmatch;
    private javax.swing.JLabel label_symbol;
    private javax.swing.JLabel label_uppercase;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_register;
    private javax.swing.JPasswordField pass_Password;
    private javax.swing.JPasswordField pass_passwordconfirmregistration;
    private javax.swing.JPasswordField pass_passwordregister;
    private javax.swing.JTextField text_Username;
    private javax.swing.JTextField txt_friendname;
    private javax.swing.JTextField txt_registeremail;
    private javax.swing.JTextField txt_registerfirstname;
    private javax.swing.JTextField txt_registerlastname;
    private javax.swing.JTextField txt_usernameregister;
    // End of variables declaration//GEN-END:variables
}
